Extension { #name : #LePageStructureAsseamblerExamples }

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetA [
	<gtExample>
	^ LeTextSnippet new
		string: 'A';
		uid: self snippetAUid
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetB [
	<gtExample>
	^ LeTextSnippet new
		string: 'B';
		uid: self snippetBUid
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetC [
	<gtExample>
	^ LeTextSnippet new
		string: 'C';
		uid: self snippetCUid
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetD [
	<gtExample>
	^ LeTextSnippet new
		string: 'D';
		uid: self snippetDUid
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetE [
	<gtExample>
	^ LeTextSnippet new
		string: 'E';
		uid: self snippetEUid
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetF [
	<gtExample>
	^ LeTextSnippet new
		string: 'F';
		uid: self snippetFUid
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetG [
	<gtExample>
	^ LeTextSnippet new
		string: 'G';
		uid: self snippetGUid
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetH [
	<gtExample>
	^ LeTextSnippet new
		string: 'H';
		uid: self snippetHUid 
]

{ #category : #'*Lepiter-Snippet-Text' }
LePageStructureAsseamblerExamples >> snippetI [
	<gtExample>
	^ LeTextSnippet new
		string: 'I';
		uid: self snippetIUid  
]
