Class {
	#name : #LeTextSnippetExampleResult,
	#superclass : #Object,
	#instVars : [
		'databaseOne',
		'databaseTwo',
		'pageOne',
		'pageTwo',
		'pageTwoSnippet'
	],
	#category : #'Lepiter-Snippet-Text-Examples'
}

{ #category : #accessing }
LeTextSnippetExampleResult >> databaseOne [
	^ databaseOne
]

{ #category : #accessing }
LeTextSnippetExampleResult >> databaseOne: anObject [
	databaseOne := anObject
]

{ #category : #accessing }
LeTextSnippetExampleResult >> databaseTwo [
	^ databaseTwo
]

{ #category : #accessing }
LeTextSnippetExampleResult >> databaseTwo: anObject [
	databaseTwo := anObject
]

{ #category : #accessing }
LeTextSnippetExampleResult >> pageOne [
	^ pageOne
]

{ #category : #accessing }
LeTextSnippetExampleResult >> pageOne: anObject [
	pageOne := anObject
]

{ #category : #accessing }
LeTextSnippetExampleResult >> pageTwo [
	^ pageTwo
]

{ #category : #accessing }
LeTextSnippetExampleResult >> pageTwo: anObject [
	pageTwo := anObject
]

{ #category : #accessing }
LeTextSnippetExampleResult >> pageTwoSnippet [
	^ pageTwoSnippet
]

{ #category : #accessing }
LeTextSnippetExampleResult >> pageTwoSnippet: anObject [
	pageTwoSnippet := anObject
]
