Class {
	#name : #LeExampleSnippetCodeExpandedChanged,
	#superclass : #LeExampleSnippetContentChanged,
	#instVars : [
		'codeExpanded'
	],
	#category : 'Lepiter-Snippet-Example-Snippet - Events'
}

{ #category : #generated }
LeExampleSnippetCodeExpandedChanged >> codeExpanded [
	<objectGetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ codeExpanded
]

{ #category : #generated }
LeExampleSnippetCodeExpandedChanged >> codeExpanded: aCodeExpanded [
	<objectSetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	codeExpanded := aCodeExpanded
]
