Class {
	#name : #LeExampleSnippetNoCodeChanged,
	#superclass : #LeExampleSnippetContentChanged,
	#instVars : [
		'noCode'
	],
	#category : 'Lepiter-Snippet-Example-Snippet - Events'
}

{ #category : #generated }
LeExampleSnippetNoCodeChanged >> noCode [
	<objectGetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ noCode
]

{ #category : #generated }
LeExampleSnippetNoCodeChanged >> noCode: aNoCode [
	<objectSetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	noCode := aNoCode
]
