Class {
	#name : #LeExampleSnippetExampleBehaviorNameChanged,
	#superclass : #LeExampleSnippetContentChanged,
	#instVars : [
		'exampleBehaviorName'
	],
	#category : 'Lepiter-Snippet-Example-Snippet - Events'
}

{ #category : #generated }
LeExampleSnippetExampleBehaviorNameChanged >> exampleBehaviorName [
	<objectGetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ exampleBehaviorName
]

{ #category : #generated }
LeExampleSnippetExampleBehaviorNameChanged >> exampleBehaviorName: aExampleBehaviorName [
	<objectSetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	exampleBehaviorName := aExampleBehaviorName
]
