Class {
	#name : #LeExampleSnippetPreviewExpandedChanged,
	#superclass : #LeExampleSnippetContentChanged,
	#instVars : [
		'previewExpanded'
	],
	#category : 'Lepiter-Snippet-Example-Snippet - Events'
}

{ #category : #generated }
LeExampleSnippetPreviewExpandedChanged >> previewExpanded [
	<objectGetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ previewExpanded
]

{ #category : #generated }
LeExampleSnippetPreviewExpandedChanged >> previewExpanded: aPreviewExpanded [
	<objectSetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	previewExpanded := aPreviewExpanded
]
