Class {
	#name : #LeExampleSnippetViewModelAnnotationCoderViewModelChanged,
	#superclass : #Announcement,
	#instVars : [
		'annotationCoderViewModel'
	],
	#category : 'Lepiter-Snippet-Example-Snippet - Events'
}

{ #category : #generated }
LeExampleSnippetViewModelAnnotationCoderViewModelChanged >> annotationCoderViewModel [
	<objectGetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ annotationCoderViewModel
]

{ #category : #generated }
LeExampleSnippetViewModelAnnotationCoderViewModelChanged >> annotationCoderViewModel: aAnnotationCoderViewModel [
	<objectSetter: #example>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	annotationCoderViewModel := aAnnotationCoderViewModel
]
