Class {
	#name : #LeChangesSnippetViewModelChangesChanged,
	#superclass : #Announcement,
	#instVars : [
		'changes'
	],
	#category : #'Lepiter-Snippet-Changes-Snippet - Events'
}

{ #category : #generated }
LeChangesSnippetViewModelChangesChanged >> changes [
	<objectGetter: #changes>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ changes
]

{ #category : #generated }
LeChangesSnippetViewModelChangesChanged >> changes: aChanges [
	<objectSetter: #changes>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	changes := aChanges
]
