Class {
	#name : #LeEditElementSnippetClearContentCommandExamples,
	#superclass : #LeEditElementSnippetCodeCommandExamples,
	#category : #'Lepiter-Snippet-Element-Examples'
}

{ #category : #accessing }
LeEditElementSnippetClearContentCommandExamples >> initialStringValue [
	^ 'BlElement new'
]

{ #category : #accessing }
LeEditElementSnippetClearContentCommandExamples >> modifiedStringValue [
	^ ''
]
