"
{{gtClass:LeEditEmptyTextSnippetCommandInStandalonePageExamples}} has examples for editing a text snippet from a page that is not inside a database.
"
Class {
	#name : #LeEditEmptyTextSnippetCommandInStandalonePageExamples,
	#superclass : #LeEditEmptyTextSnippetCommandExamples,
	#traits : 'TLeContentCommandInStandalonePageExamples',
	#classTraits : 'TLeContentCommandInStandalonePageExamples classTrait',
	#category : #'Lepiter-History-Examples - Commands'
}
