Class {
	#name : #LeEditEmptyPharoSnippetCommandInStandalonePageExamples,
	#superclass : #LeEditPharoSnippetCommandExamples,
	#category : #'Lepiter-History-Examples - Commands'
}

{ #category : #accessing }
LeEditEmptyPharoSnippetCommandInStandalonePageExamples >> initialStringValue [
	^ ''
]

{ #category : #accessing }
LeEditEmptyPharoSnippetCommandInStandalonePageExamples >> modifiedStringValue [
	^ '1+1'
]
